django_qldh/urls.py
from django.contrib import admin
from django.urls import path, include
from django_qldh import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('qldh/', include('qldh.urls', namespace='QLDH'), name='qldh'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
import home.views as views


urlpatterns = [
    path('', views.index, name='home_page'),
]

qldh/urls.py
from django.urls import path, include
from . import views
from . import AdminView, TeacherView, StudentView

app_name = 'QLDH'
urlpatterns = [
    path('', views.loginPage, name="login"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', AdminView.admin_home, name="admin_home"),
    path('check_email_exist/', AdminView.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', AdminView.check_username_exist, name="check_username_exist"),
    path('download_excel/<file_name>', AdminView.download_excel, name="download_excel"),

    path('quan_ly_giao_vien/', AdminView.manage_teacher, name="manage_teacher"),
    path('admin_get_teacher/', AdminView.admin_get_teacher, name="admin_get_teacher"),
    path('them_moi_giao_vien_xls/', AdminView.add_teacher_from_xls, name="add_teacher_from_xls"),
    path('luu_them_moi_giao_vien/', AdminView.add_teacher_save, name="add_teacher_save"),
    path('chinh_sua_giao_vien/<magv>/', AdminView.edit_teacher, name="edit_teacher"),
    path('luu_chinh_sua_giao_vien/', AdminView.edit_teacher_save, name="edit_teacher_save"),
    path('xoa_giao_vien/<magv>/', AdminView.delete_teacher, name="delete_teacher"),
    path('quan_ly_phong_hoc/', AdminView.manage_study_room, name="manage_study_room"),
    path('admin_get_classroom/', AdminView.admin_get_classroom, name="admin_get_classroom"),
    path('them_moi_phong_hoc_xls/', AdminView.add_study_room_from_xls, name="add_study_room_from_xls"),
    path('luu_them_moi_phong_hoc/', AdminView.add_study_room_save, name="add_study_room_save"),
    path('chinh_sua_phong_hoc/<ma_phong>/', AdminView.edit_study_room, name="edit_study_room"),
    path('luu_chinh_sua_phong_hoc/', AdminView.edit_study_room_save, name="edit_study_room_save"),
    path('xoa_phong_hoc/<ma_phong>/', AdminView.delete_study_room, name="delete_study_room"),
    path('quan_ly_lop_hoc/', AdminView.manage_classroom, name="manage_classroom"),
    path('them_moi_lop_hoc_xls/', AdminView.add_classroom_from_xls, name="add_classroom_from_xls"),
    path('luu_them_moi_lop_hoc/', AdminView.add_classroom_save, name="add_classroom_save"),
    path('chinh_sua_lop_hoc/<ma_lop>/', AdminView.edit_classroom, name="edit_classroom"),
    path('luu_chinh_sua_lop_hoc/', AdminView.edit_classroom_save, name="edit_classroom_save"),
    path('xoa_lop_hoc/<ma_lop>/', AdminView.delete_classroom, name="delete_classroom"),

    path('admin_get_student/', AdminView.admin_get_student, name="admin_get_student"),
    path('quan_ly_hoc_sinh/', AdminView.manage_student, name="manage_student"),
    path('them_moi_hoc_sinh_xls/', AdminView.add_student_from_xls, name="add_student_from_xls"),
    path('luu_them_moi_hoc_sinh/', AdminView.add_student_save, name="add_student_save"),
    path('chinh_sua_hoc_sinh/<mahs>/', AdminView.edit_student, name="edit_student"),
    path('luu_chinh_sua_hoc_sinh/', AdminView.edit_student_save, name="edit_student_save"),
    path('xoa_hoc_sinh/<mahs>/', AdminView.delete_student, name="delete_student"),

    path('get_teacher/', AdminView.get_teacher, name="get_teacher"),

    path('quan_ly_giang_day/', AdminView.manage_tuition, name="manage_tuition"),
    path('them_moi_giang_day_ajax/', AdminView.them_moi_giang_day, name="them_moi_giang_day_ajax"),
    path('chinh_sua_lop_giang_day_ajax/', AdminView.chinh_sua_lop_giang_day, name="chinh_sua_lop_giang_day_ajax"),
    path('xoa_giang_day_ajax/', AdminView.xoa_giang_day, name="xoa_giang_day_ajax"),

    path('admin_get_tuition_new/', AdminView.get_tuition, name="get_tuition"),
    path('quan_ly_mon_hoc/', AdminView.manage_subject, name="manage_subject"),
    path('kiem_tra_ma_mon/', AdminView.kiem_tra_ma_mon, name="kiem_tra_ma_mon"),
    path('kiem_tra_ten_mon/', AdminView.kiem_tra_ten_mon, name="kiem_tra_ten_mon"),
    path('them_moi_mon_hoc_xls/', AdminView.add_subject_from_xls, name="add_subject_from_xls"),
    path('luu_them_moi_mon_hoc/', AdminView.add_subject_save, name="add_subject_save"),
    path('chinh_sua_mon_hoc/<ma_mon>/', AdminView.edit_subject, name="edit_subject"),
    path('luu_chinh_sua_mon_hoc/<ma_mon>/', AdminView.edit_subject_save, name="edit_subject_save"),
    path('xoa_mon_hoc/<ma_mon>/', AdminView.delete_subject, name="delete_subject"),

    # URLS for GiaoVien
    path('teacher_get_tuition/', TeacherView.teacher_get_tuition, name="teacher_get_tuition"),
    path('teacher_home/', TeacherView.teacher_home, name="teacher_home"),
    path('danh_sach_giang_day/', TeacherView.view_tuition, name="view_tuition"),
    path('tai_xuong_tkb/', TeacherView.tkb_gv_pdf, name="tkb_gv_pdf"),
    path('danh_sach_hoc_sinh_chu_nhiem/', TeacherView.view_student, name="view_student"),
    path('tai_xuong_dshs_cn/', TeacherView.dshs_cn_pdf, name="dshs_cn_pdf"),
    path('quan_ly_diem_so/', TeacherView.manage_mark, name="manage_mark"),
    path('lay_ds_ajax/', TeacherView.lay_danh_sach_hoc_sinh, name="lay_ds_ajax"),
    path('luu_diem_so/', TeacherView.luu_diem_so, name="luu_diem_so"),
    path('bang_diem_pdf/<ma_lop>/', TeacherView.bang_diem_pdf, name="bang_diem_pdf"),
    path('get_hanh_kiem_ajax/', TeacherView.get_hanh_kiem_ajax, name="get_hanh_kiem_ajax"),
    path('danh_gia_hanh_kiem/', TeacherView.danh_gia_hanh_kiem, name="assessment_student"),
    path('luu_hanh_kiem/', TeacherView.luu_hanh_kiem, name="luu_hanh_kiem"),
    path('bang_hanh_kiem_pdf/', TeacherView.bang_hanh_kiem_pdf, name="bang_hanh_kiem_pdf"),
    path('thong_tin_ca_nhan/', TeacherView.profile_teacher, name="profile_teacher"),
    path('luu_doi_mat_khau/', TeacherView.luu_doi_mat_khau, name="luu_doi_mat_khau"),

    # URLS for HocSinh
    path('student_home/', StudentView.student_home, name="student_home"),
    path('xem_thong_tin_lop_hoc/', StudentView.view_classroom, name="view_classroom"),
    path('xem_thoi_khoa_bieu/', StudentView.xem_tkb, name="xem_tkb"),
    path('tai_xuong_tkb_hs/', StudentView.tkb_hs_pdf, name="tkb_hs_pdf"),
    path('student_get_tuition/', StudentView.student_get_tuition, name="student_get_tuition"),
    path('xem_diem_so_ca_nhan/', StudentView.view_personal_mark, name="view_personal_mark"),
    path('tai_xuong_bang_diem_hs/', StudentView.bang_diem_hs_pdf, name="bang_diem_hs_pdf"),
    path('thong_tin_ca_nhan_hoc_sinh/', StudentView.profile_student, name="profile_student"),
    path('luu_doi_mat_khau_hoc_sinh/', StudentView.luu_doi_mat_khau_hoc_sinh, name="luu_doi_mat_khau_hoc_sinh"),
]

home/models.py
from django.db import models
# Create your models here.


class TinTuc(models.Model):
    tieu_de = models.CharField(max_length=255, default='')
    ngay_tao = models.DateTimeField(auto_now_add=True)
    tao_boi = models.ForeignKey('qldh.AdminUser', on_delete=models.CASCADE)
    noi_dung = models.TextField(max_length=1000)

home/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'home.html')

home/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Trang chủ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" type="text/css" media="screen"
          href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'home/main.css' %}"/>
</head>
<body>
<main>
    <header class="p-1 mb-3 border-bottom">
        <div class="p-1 text-center bg-image">
            <img class="img-fluid" src="{% static 'home/img/title_img.jpg' %}" alt=""/>
        </div>
        <!-- navbar -->
        <nav
                class="navbar navbar-expand-xl navbar-light bg-light"
        >
            <div class="container justify-content-xl-center" style="width: 1050px;">
                <a
                        href="/"
                        class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none"
                >
                    <i class="fas fa-home me-3"></i>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarsExample03"
                        aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample03">
                    <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#"
                            >Giới thiệu</a
                            >
                        </li>
                        <li class="nav-item dropdown">
                            <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    id="dropdown03"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false"
                            >Thông báo - Văn bản</a
                            >
                            <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                <li><a class="dropdown-item" href="#">Thông báo</a></li>
                                <li>
                                    <a class="dropdown-item" href="#">Văn bản</a>
                                </li>
                            </ul>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Thi - Kiểm tra</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'QLDH:login' %}">Hệ thống quản lý</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Liên hệ</a>
                        </li>
                        </li>
                    </ul>
                    <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                        <input
                                type="search"
                                class="form-control form-control-dark"
                                placeholder="Search..."
                        />
                    </form>
                    <div class="text-end">
                        <button type="button" class="btn btn-primary" onClick="{% url 'QLDH:login' %}">Đăng nhập</button>
                    </div>
                </div>
            </div>
        </nav>
        <!-- navbar -->
    </header>
    <div class="container">
        <div class="post-feature">
            <a href="#" class="post-feature-media post-media">
                <img src="https://images.unsplash.com/photo-1643391068885-de678170209a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=599&q=80"
                     alt="" class="post-feature-image">
            </a>
            <div class="post-feature-info">
                <h2>
                    <a href="#" class="post-feature-title post-title">Thông báo lịch thi học kì II - Năm học 2021 - 2022</a>
                </h2>
                <p class="post-desc">Lịch thi học kì II - Năm học 2021 - 2022 ....</p>
            </div>
        </div>
        <div class="post-list">
            <div class="post-item">
                <a href="#" class="post-media"><img
                        src="https://images.unsplash.com/photo-1643391068885-de678170209a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=599&q=80"
                        alt="" class="post-image"></a>
                <h3>
                    <a href="#" class="post-title">This is title</a>
                </h3>
                <p class="post-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis rerum sunt quia
                    veritatis odit harum accusamus ipsa nobis nulla doloribus, labore aliquid eaque praesentium pariatur
                    ut a! Sapiente, eaque ipsam.</p>
            </div>
            <div class="post-item">
                <a href="#" class="post-media"><img
                        src="https://images.unsplash.com/photo-1643391068885-de678170209a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=599&q=80"
                        alt="" class="post-image"></a>
                <h3>
                    <a href="#" class="post-title">This is title</a>
                </h3>
                <p class="post-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis rerum sunt quia
                    veritatis odit harum accusamus ipsa nobis nulla doloribus, labore aliquid eaque praesentium pariatur
                    ut a! Sapiente, eaque ipsam.</p>
            </div>
            <div class="post-item">
                <a href="#" class="post-media"><img
                        src="https://images.unsplash.com/photo-1643391068885-de678170209a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=599&q=80"
                        alt="" class="post-image"></a>
                <h3>
                    <a href="#" class="post-title">This is title</a>
                </h3>
                <p class="post-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis rerum sunt quia
                    veritatis odit harum accusamus ipsa nobis nulla doloribus, labore aliquid eaque praesentium pariatur
                    ut a! Sapiente, eaque ipsam.</p>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Links  -->
        <section class="d-flex justify-content-center justify-content-lg-between border-bottom">
            <div class="container text-center text-md-start mt-3" style="width: 1050px;">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>Trường THPT ABC
                        </h6>
                        <p>
                            Có lịch sử lâu đời với hơn 150 giáo viên và 1300 học sinh hiện đang học tập và làm việc tại
                            trường.
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Liên hệ
                        </h6>
                        <p><i class="fas fa-home me-3"></i> Ninh Kiều, Cần Thơ</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            info@abc.edu.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> + 84 123 456 789</p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->

        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2021 Copyright:
            <a class="text-reset fw-bold" href="#">Thang Quoc</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
</main>
<script src="{% static 'home/main.js' %}"></script>
<script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>