django_qldh/urls.py
from django.contrib import admin
from django.urls import path, include
from django_qldh import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('qldh/', include('qldh.urls', namespace='QLDH'), name='qldh'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
import home.views as views


urlpatterns = [
    path('', views.index, name='home_page'),
]

qldh/urls.py
from django.urls import path, include
from . import views
from . import AdminView, TeacherView, StudentView

app_name = 'QLDH'
urlpatterns = [
    path('', views.loginPage, name="login"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', AdminView.admin_home, name="admin_home"),
    path('check_email_exist/', AdminView.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', AdminView.check_username_exist, name="check_username_exist"),
    path('download_excel/<file_name>', AdminView.download_excel, name="download_excel"),

    path('quan_ly_giao_vien/', AdminView.manage_teacher, name="manage_teacher"),
    path('admin_get_teacher/', AdminView.admin_get_teacher, name="admin_get_teacher"),
    path('them_moi_giao_vien_xls/', AdminView.add_teacher_from_xls, name="add_teacher_from_xls"),
    path('luu_them_moi_giao_vien/', AdminView.add_teacher_save, name="add_teacher_save"),
    path('chinh_sua_giao_vien/<magv>/', AdminView.edit_teacher, name="edit_teacher"),
    path('luu_chinh_sua_giao_vien/', AdminView.edit_teacher_save, name="edit_teacher_save"),
    path('xoa_giao_vien/<magv>/', AdminView.delete_teacher, name="delete_teacher"),
    path('quan_ly_phong_hoc/', AdminView.manage_study_room, name="manage_study_room"),
    path('admin_get_classroom/', AdminView.admin_get_classroom, name="admin_get_classroom"),
    path('them_moi_phong_hoc_xls/', AdminView.add_study_room_from_xls, name="add_study_room_from_xls"),
    path('luu_them_moi_phong_hoc/', AdminView.add_study_room_save, name="add_study_room_save"),
    path('chinh_sua_phong_hoc/<ma_phong>/', AdminView.edit_study_room, name="edit_study_room"),
    path('luu_chinh_sua_phong_hoc/', AdminView.edit_study_room_save, name="edit_study_room_save"),
    path('xoa_phong_hoc/<ma_phong>/', AdminView.delete_study_room, name="delete_study_room"),
    path('quan_ly_lop_hoc/', AdminView.manage_classroom, name="manage_classroom"),
    path('them_moi_lop_hoc_xls/', AdminView.add_classroom_from_xls, name="add_classroom_from_xls"),
    path('luu_them_moi_lop_hoc/', AdminView.add_classroom_save, name="add_classroom_save"),
    path('chinh_sua_lop_hoc/<ma_lop>/', AdminView.edit_classroom, name="edit_classroom"),
    path('luu_chinh_sua_lop_hoc/', AdminView.edit_classroom_save, name="edit_classroom_save"),
    path('xoa_lop_hoc/<ma_lop>/', AdminView.delete_classroom, name="delete_classroom"),

    path('admin_get_student/', AdminView.admin_get_student, name="admin_get_student"),
    path('quan_ly_hoc_sinh/', AdminView.manage_student, name="manage_student"),
    path('them_moi_hoc_sinh_xls/', AdminView.add_student_from_xls, name="add_student_from_xls"),
    path('luu_them_moi_hoc_sinh/', AdminView.add_student_save, name="add_student_save"),
    path('chinh_sua_hoc_sinh/<mahs>/', AdminView.edit_student, name="edit_student"),
    path('luu_chinh_sua_hoc_sinh/', AdminView.edit_student_save, name="edit_student_save"),
    path('xoa_hoc_sinh/<mahs>/', AdminView.delete_student, name="delete_student"),

    path('get_teacher/', AdminView.get_teacher, name="get_teacher"),

    path('quan_ly_giang_day/', AdminView.manage_tuition, name="manage_tuition"),
    path('them_moi_giang_day_ajax/', AdminView.them_moi_giang_day, name="them_moi_giang_day_ajax"),
    path('chinh_sua_lop_giang_day_ajax/', AdminView.chinh_sua_lop_giang_day, name="chinh_sua_lop_giang_day_ajax"),
    path('xoa_giang_day_ajax/', AdminView.xoa_giang_day, name="xoa_giang_day_ajax"),

    path('admin_get_tuition_new/', AdminView.get_tuition, name="get_tuition"),
    path('quan_ly_mon_hoc/', AdminView.manage_subject, name="manage_subject"),
    path('kiem_tra_ma_mon/', AdminView.kiem_tra_ma_mon, name="kiem_tra_ma_mon"),
    path('kiem_tra_ten_mon/', AdminView.kiem_tra_ten_mon, name="kiem_tra_ten_mon"),
    path('them_moi_mon_hoc_xls/', AdminView.add_subject_from_xls, name="add_subject_from_xls"),
    path('luu_them_moi_mon_hoc/', AdminView.add_subject_save, name="add_subject_save"),
    path('chinh_sua_mon_hoc/<ma_mon>/', AdminView.edit_subject, name="edit_subject"),
    path('luu_chinh_sua_mon_hoc/<ma_mon>/', AdminView.edit_subject_save, name="edit_subject_save"),
    path('xoa_mon_hoc/<ma_mon>/', AdminView.delete_subject, name="delete_subject"),

    # URLS for GiaoVien
    path('teacher_get_tuition/', TeacherView.teacher_get_tuition, name="teacher_get_tuition"),
    path('teacher_home/', TeacherView.teacher_home, name="teacher_home"),
    path('danh_sach_giang_day/', TeacherView.view_tuition, name="view_tuition"),
    path('tai_xuong_tkb/', TeacherView.tkb_gv_pdf, name="tkb_gv_pdf"),
    path('danh_sach_hoc_sinh_chu_nhiem/', TeacherView.view_student, name="view_student"),
    path('tai_xuong_dshs_cn/', TeacherView.dshs_cn_pdf, name="dshs_cn_pdf"),
    path('quan_ly_diem_so/', TeacherView.manage_mark, name="manage_mark"),
    path('lay_ds_ajax/', TeacherView.lay_danh_sach_hoc_sinh, name="lay_ds_ajax"),
    path('luu_diem_so/', TeacherView.luu_diem_so, name="luu_diem_so"),
    path('bang_diem_pdf/<ma_lop>/', TeacherView.bang_diem_pdf, name="bang_diem_pdf"),
    path('get_hanh_kiem_ajax/', TeacherView.get_hanh_kiem_ajax, name="get_hanh_kiem_ajax"),
    path('danh_gia_hanh_kiem/', TeacherView.danh_gia_hanh_kiem, name="assessment_student"),
    path('luu_hanh_kiem/', TeacherView.luu_hanh_kiem, name="luu_hanh_kiem"),
    path('bang_hanh_kiem_pdf/', TeacherView.bang_hanh_kiem_pdf, name="bang_hanh_kiem_pdf"),
    path('thong_tin_ca_nhan/', TeacherView.profile_teacher, name="profile_teacher"),
    path('luu_doi_mat_khau/', TeacherView.luu_doi_mat_khau, name="luu_doi_mat_khau"),

    # URLS for HocSinh
    path('student_home/', StudentView.student_home, name="student_home"),
    path('xem_thong_tin_lop_hoc/', StudentView.view_classroom, name="view_classroom"),
    path('xem_thoi_khoa_bieu/', StudentView.xem_tkb, name="xem_tkb"),
    path('tai_xuong_tkb_hs/', StudentView.tkb_hs_pdf, name="tkb_hs_pdf"),
    path('student_get_tuition/', StudentView.student_get_tuition, name="student_get_tuition"),
    path('xem_diem_so_ca_nhan/', StudentView.view_personal_mark, name="view_personal_mark"),
    path('tai_xuong_bang_diem_hs/', StudentView.bang_diem_hs_pdf, name="bang_diem_hs_pdf"),
    path('thong_tin_ca_nhan_hoc_sinh/', StudentView.profile_student, name="profile_student"),
    path('luu_doi_mat_khau_hoc_sinh/', StudentView.luu_doi_mat_khau_hoc_sinh, name="luu_doi_mat_khau_hoc_sinh"),
]

qldh/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.


class CustomUser(AbstractUser):
    user_type_data = ((1, "Admin"), (2, "Giáo Viên"), (3, "Học Sinh"))
    user_type = models.IntegerField(default=1, choices=user_type_data)

    def get_full_name(self):
        return self.last_name + " " + self.first_name


class AdminUser(models.Model):
    ma_admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, to_field='username', primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()


class TrinhDoHocVan(models.Model):
    trinh_do = models.CharField(max_length=40, primary_key=True)
    mo_ta_trinh_do = models.CharField(default='', max_length=250, unique=True)
    objects = models.Manager()


class PhongHoc(models.Model):
    ma_phong = models.CharField(max_length=8, default='', primary_key=True)
    ten_phong = models.CharField(max_length=50, default='', unique=True)
    so_luong_cho_ngoi = models.IntegerField(default=0)
    objects = models.Manager()

    def get_id(self):
        return self.ma_phong


class MonHoc(models.Model):
    ma_mon = models.CharField(primary_key=True, max_length=5, null=False)
    ten_mon = models.CharField(max_length=50, default='', unique=True, null=False)
    tiet_tuan = models.IntegerField(default=0, null=False)
    objects = models.Manager()


class NamHoc(models.Model):
    nam_hoc = models.CharField(max_length=50, primary_key=True)
    mo_ta = models.CharField(default='', max_length=255, unique=True)
    hien_tai = models.BooleanField(default=False)
    objects = models.Manager()

    def __str__(self):
        return self.nam_hoc + '(' + self.mo_ta + ')'


class HocKy(models.Model):
    hoc_ky = models.CharField(max_length=1, primary_key=True)
    hien_tai = models.BooleanField(default=False)
    objects = models.Manager()

    def __str__(self):
        return "Học Kỳ " + self.hoc_ky


class GiaoVien(models.Model):
    magv = models.OneToOneField(CustomUser, on_delete=models.CASCADE, to_field='username', primary_key=True)
    so_dien_thoai = models.CharField(max_length=10, default='', null=True)
    trinh_do = models.ForeignKey(TrinhDoHocVan, on_delete=models.CASCADE)
    que_quan = models.TextField(default='')
    ngay_sinh = models.DateField(default=datetime(1900, 1, 1))
    gioi_tinh = models.CharField(max_length=50, default='')
    day_mon = models.ForeignKey(MonHoc, on_delete=models.CASCADE)
    objects = models.Manager()

    def get_id(self):
        return self.magv


class LopHoc(models.Model):
    ma_lop = models.CharField(primary_key=True, max_length=8, default='')
    ten_lop = models.CharField(max_length=50, default='', unique=True)
    phong = models.OneToOneField(PhongHoc, on_delete=models.CASCADE)
    si_so = models.IntegerField(default=0)
    giao_vien_chu_nhiem = models.OneToOneField(GiaoVien, on_delete=models.CASCADE)
    khoi = models.CharField(max_length=50)
    nam_hoc = models.ForeignKey(NamHoc, on_delete=models.CASCADE, null=True)
    requestId = models.TextField(default="")
    meetLink = models.TextField(default="")
    id_cal_lh = models.TextField(default="")
    objects = models.Manager()

    def get_id(self):
        return self.ma_lop


class HocSinh(models.Model):
    mahs = models.OneToOneField(CustomUser, on_delete=models.CASCADE, to_field='username', primary_key=True)
    lop = models.ForeignKey(LopHoc, on_delete=models.DO_NOTHING)
    que_quan = models.TextField()
    ngay_sinh = models.DateField(default=datetime(1900, 1, 1))
    gioi_tinh = models.CharField(max_length=50)
    dan_toc = models.CharField(max_length=50)
    objects = models.Manager()

    def get_id(self):
        return self.mahs


class GiangDay(models.Model):
    magv = models.ForeignKey(GiaoVien, on_delete=models.CASCADE)
    thu = models.IntegerField(null=False, default=8,
                              validators=[MaxValueValidator(7),
                                          MinValueValidator(2)]
                              )
    ma_lop = models.ForeignKey(LopHoc, on_delete=models.CASCADE)

    nam_hoc = models.ForeignKey(NamHoc, on_delete=models.CASCADE)
    hoc_ky = models.ForeignKey(HocKy, on_delete=models.CASCADE, default="0")

    tiet_1 = models.BooleanField(default=False, blank=True)
    tiet_2 = models.BooleanField(default=False, blank=True)
    tiet_3 = models.BooleanField(default=False, blank=True)
    tiet_4 = models.BooleanField(default=False, blank=True)
    tiet_5 = models.BooleanField(default=False, blank=True)
    tiet_6 = models.BooleanField(default=False, blank=True)
    tiet_7 = models.BooleanField(default=False, blank=True)
    tiet_8 = models.BooleanField(default=False, blank=True)
    tiet_9 = models.BooleanField(default=False, blank=True)
    cal_id = models.TextField(default="")
    objects = models.Manager()

    class Meta:
        unique_together = (('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_1', 'tiet_2', 'tiet_3', 'tiet_4', 'tiet_5'
                            , 'tiet_6', 'tiet_7', 'tiet_8', 'tiet_9'),)


class HanhKiem(models.Model):
    mahs = models.ForeignKey(HocSinh, on_delete=models.CASCADE)
    hanh_kiem_data = ((1, "Giỏi"), (2, "Khá"), (3, "Trung Bình"), (4, "Yếu"), (5, "Kém"), (-1, "Chưa đánh giá"))
    hanh_kiem = models.IntegerField(default=-1, choices=hanh_kiem_data)
    nam_hoc = models.ForeignKey(NamHoc, on_delete=models.CASCADE)
    hoc_ky = models.ForeignKey(HocKy, on_delete=models.CASCADE, default="0")
    objects = models.Manager()


class DiemSo(models.Model):
    mahs = models.ForeignKey(HocSinh, on_delete=models.CASCADE)
    nam_hoc = models.ForeignKey(NamHoc, on_delete=models.CASCADE)
    hoc_ky = models.ForeignKey(HocKy, on_delete=models.CASCADE, default="0")
    mon = models.ForeignKey(MonHoc, on_delete=models.CASCADE)
    m1 = models.FloatField(default=0.0)
    m2 = models.FloatField(default=0.0)
    m3 = models.FloatField(default=0.0)
    p1 = models.FloatField(default=0.0)
    p2 = models.FloatField(default=0.0)
    p3 = models.FloatField(default=0.0)
    p4 = models.FloatField(default=0.0)
    t1 = models.FloatField(default=0.0)
    t2 = models.FloatField(default=0.0)
    t3 = models.FloatField(default=0.0)
    t4 = models.FloatField(default=0.0)
    t5 = models.FloatField(default=0.0)
    t6 = models.FloatField(default=0.0)
    t7 = models.FloatField(default=0.0)
    t8 = models.FloatField(default=0.0)
    hk = models.FloatField(default=0.0)
    tb = models.FloatField(default=0.0, null=True)
    objects = models.Manager()

    def save(self, *args, **kwargs):
        self.tb = round((float(self.m1) + float(self.m2) + float(self.m3) + float(self.p1) + float(self.p2) + float(
            self.p3) + float(self.p4) + ((float(self.t1) + float(self.t2) + float(self.t3) + float(self.t4) +
                                          float(self.t5) + float(self.t6) + float(self.t7) + float(self.t8)) * 2) +
                         (float(self.hk) * 3)) / 26, 2)
        super(DiemSo, self).save(*args, **kwargs)


# Creating Django Signals

# It's like trigger in database. It will run only when Data is Added in CustomUser model

@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    # if Created is true (Means Data Inserted)
    if created:
        # Check the user_type and insert the data in respective tables
        if instance.user_type == 1:
            AdminUser.objects.create(ma_admin=instance)
        if instance.user_type == 2:
            GiaoVien.objects.create(magv=instance, trinh_do=TrinhDoHocVan.objects.get(trinh_do="TC"),
                                    day_mon=MonHoc.objects.get(ma_mon="GDCD"))
        if instance.user_type == 3:
            HocSinh.objects.create(mahs=instance, lop=LopHoc.objects.get(ma_lop="LH000001"))


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.adminuser.save()
    if instance.user_type == 2:
        instance.giaovien.save()
    if instance.user_type == 3:
        instance.hocsinh.save()

qldh/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages

# Create your views here.


def index(request):
    return render(request, 'index.html')


def loginPage(request):
    return render(request, 'login.html')


def doLogin(request):
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = authenticate(request, username=request.POST.get('username'), password=request.POST.get('password'))
        if user is not None:
            login(request, user)
            user_type = user.user_type
            # return HttpResponse("Username: "+request.POST.get('username') + " Password: "+request.POST.get('password'))
            if user_type == 1:
                return redirect('QLDH:admin_home')
            elif user_type == 2:
                # return HttpResponse("Teacher Login")
                return redirect('QLDH:teacher_home')
            elif user_type == 3:
                # return HttpResponse("Student Login")
                return redirect('QLDH:student_home')
            else:
                messages.error(request, "Bạn không có quyền đăng nhập!")
                return redirect('QLDH:login')
        else:
            messages.error(request, "Thông tin đăng nhập không hợp lệ!")
            # return HttpResponseRedirect("/")
            return redirect('QLDH:login')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/qldh/')

qldh/templates/student_templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hệ thống quản lý dạy học | Học sinh</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"/>
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Bootstrap 5 -->
    <link rel="stylesheet" href="{% static "bootstrap-5.1.3-dist/css/bootstrap.css" %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static "icheck-bootstrap/icheck-bootstrap.min.css" %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static "jqvmap/jqvmap.min.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static "overlayScrollbars/css/OverlayScrollbars.min.css" %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static "daterangepicker/daterangepicker.css" %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static "summernote/summernote-bs4.css" %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    {% comment %} For Custom CSS {% endcomment %}

    {% block custom_css %}
    {% endblock custom_css %}

</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" id="hide_sidebar" data-widget="pushmenu" href="#" role="button"><i
                        class="fas fa-bars"></i></a>
            </li>
        </ul>

        <h4 style="margin-left: 10px; margin-top: 5px;">Hệ Thống Quản Lý Dạy Học </h4>

        <ul class="navbar-nav ml-auto">

            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-cog"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'QLDH:logout_user' %}"><i class="fas fa-power-off mr-2"></i>
                        Đăng xuất</a></li>
                    {#            <li><a class="dropdown-item" href="#">Another action</a></li>#}
                    {#            <li><a class="dropdown-item" href="#">Something else here</a></li>#}
                </ul>
            </li>
        </ul>

    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    {% include 'student_templates/sidebar_template.html' with user=user id=id %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">


        <!-- Main content -->
        {% block main_content %}
        {% endblock main_content %}
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    {% include 'student_templates/footer.html' %}


</div>
<!-- ./wrapper -->


<!-- jQuery -->
<script src="{% static "jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 5 -->
<script src="{% static "bootstrap-5.1.3-dist/js/bootstrap.bundle.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "jqvmap/maps/jquery.vmap.usa.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "moment/moment.min.js" %}"></script>
<script src="{% static "daterangepicker/daterangepicker.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
  <script>
            document.getElementById('hide_sidebar').click();
    </script>
{% comment %} For Custom JS {% endcomment %}
{% block custom_js %}
{% endblock custom_js %}

</body>
</html>

qldh/templates/student_templates/footer.html
<footer class="main-footer">
      <strong>Copyright &copy; {% now "Y" %}, <a href="#">Banh Quoc Thang</a>.</strong>
      All rights reserved.
      <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0
      </div>
    </footer>

qldh/templates/student_templates/sidebar_template.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="{% url 'QLDH:student_home' %}" class="brand-link">
        <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">ESchool</span>
      </a>

      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
          </div>
          <div class="info">
            <a href="{% url 'QLDH:student_home' %}" class="d-block">{{ user.last_name }} {{ user.first_name }}</a>
          </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false" id="siderbar" name="siderbar">
            <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->

            <li class="nav-item">
              {% url 'QLDH:student_home' as student_home %}
              <a href="{{ student_home }}" class="nav-link {% if request.path == student_home %} active {% endif %}">
                <i class="nav-icon fas fa-school"></i>
                <p>
                  Trang chủ
                </p>
              </a>
            </li>

            <li class="nav-item">
              {% url 'QLDH:view_classroom' as view_classroom %}
              <a href="{{ view_classroom }}" class="nav-link {% if request.path == view_classroom %} active {% endif %}">
                <i class="nav-icon fas fa-chalkboard-teacher"></i>
                <p>
                  Lớp học - Hạnh kiểm
                </p>
              </a>
            </li>

          <li class="nav-item">
              {% url 'QLDH:xem_tkb' as xem_tkb %}
              <a href="{{ xem_tkb }}" class="nav-link {% if request.path == xem_tkb %} active {% endif %}">
                <i class="nav-icon fas fa-chalkboard-teacher"></i>
                <p>
                  Thời khóa biểu
                </p>
              </a>
            </li>

            <li class="nav-item">
              {% url 'QLDH:view_personal_mark' as view_personal_mark %}
              <a href="{{ view_personal_mark }}" class="nav-link {% if request.path == view_personal_mark %} active {% endif %}">
                <i class="nav-icon fas fa-th"></i>
                <p>
                  Điểm số cá nhân
                </p>
              </a>
            </li>

            <li class="nav-item">
              {% url 'QLDH:profile_student' as profile_student %}
              <a href="{{ profile_student }}" class="nav-link {% if request.path == profile_student %} active {% endif %}">
                <i class="nav-icon fas fa-user"></i>
                <p>
                  Thông tin cá nhân
                </p>
              </a>
            </li>
          </ul>
        </nav>
        <!-- /.sidebar-menu -->

      </div>
      <!-- /.sidebar -->
    </aside>